# Generated by Django 4.0.8 on 2022-11-29 05:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_button_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_first_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_second_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_overlay_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_overlay_text',
            field=wagtail.fields.RichTextField(default='helo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_field',
            field=wagtail.fields.StreamField([('carousel', wagtail.blocks.StructBlock([('carousel', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.blocks.RichTextBlock(blank=True))]), blank=True))]))], blank=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_of_section_1',
            field=wagtail.fields.RichTextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_of_section_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheading_of_section_1',
            field=wagtail.fields.RichTextField(default='by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box1_image_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box1_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box1_text_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box2_image_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box2_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box2_text_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box3_image_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box3_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box3_text_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box4_image_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box4_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='volunteers_box4_text_section_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
