# Generated by Django 4.0.8 on 2022-11-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_carousel_field_homepage_image_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image_gallery',
            new_name='carousel_field',
        ),
    ]
