# Generated by Django 4.0.8 on 2022-11-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_image_gallery_homepage_carousel_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='carousel_field',
        ),
    ]
