# Generated by Django 4.0.8 on 2022-11-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_imagegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Image Gallery'},
        ),
    ]
