# Generated by Django 4.0.8 on 2022-11-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0007_alter_imagegallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_university_address', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Image Gallery',
            },
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
