# Generated by Django 4.0.8 on 2022-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_nila_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='proffesion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
