# Generated by Django 4.0.8 on 2022-12-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_carouselitem_id_alter_leaderboard_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name': 'ImageGallery'},
        ),
    ]
