# Generated by Django 4.0.8 on 2022-12-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_leaderboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name': 'LeaderBoard_Section'},
        ),
    ]
