# Generated by Django 4.0.8 on 2023-01-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_leaderboard_is_showing'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='assignment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='signatures',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='student_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='volunteehours',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
