# Generated by Django 4.0.8 on 2023-01-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0016_leaderboard_assignment_leaderboard_signatures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('signatures', models.IntegerField(default=0)),
                ('leader_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'LeaderBoard_Score',
            },
        ),
    ]
