# Generated by Django 3.2.16 on 2023-01-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_leaderboard_student_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='signatures',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='student_description',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='volunteehours',
        ),
    ]
