# Generated by Django 4.0.8 on 2023-01-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_leaderboardscoreboard'),
        ('home', '0018_auto_20230110_0550'),
    ]

    operations = [
    ]
