# Generated by Django 4.0.8 on 2023-02-01 10:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_merge_20230116_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='student_description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
