# Generated by Django 4.0.8 on 2022-12-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_registerform_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='name_of_school',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='state',
        ),
    ]
