# Generated by Django 4.0.8 on 2022-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_registerform_grade_level_registerform_name_of_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='flexRadioDefault',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
