# Generated by Django 4.0.8 on 2022-12-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_fourdivsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FourDivSection',
        ),
    ]
