# Generated by Django 3.2.16 on 2023-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_signandshareform_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signandshareform',
            name='count',
            field=models.CharField(max_length=10000000),
        ),
    ]
