# Generated by Django 3.2.16 on 2023-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_flexpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('name_of_school', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('areyoua', models.CharField(max_length=200)),
            ],
        ),
    ]
