# Generated by Django 4.0.8 on 2022-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='icon',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
