# Generated by Django 4.0.8 on 2022-11-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('menu', '0005_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_icon',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
