# Generated by Django 4.0.8 on 2022-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_footer_footer_icon_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_icon_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
