# Generated by Django 4.0.8 on 2022-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_footer_address_footer_email_footer_footer_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
