# Generated by Django 4.0.8 on 2022-12-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_footer_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
