# Generated by Django 4.0.8 on 2022-12-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
